### ISSUE TITLE
Missed algoliaAdminBundle.js and broken js in backend

### ISSUE THREAD

**Issue by vmalyk** [algolia/algoliasearch-magento-2#167]
**Preconditions**
 1. Magento CE and EE 2.1.4.
 2. Module version 1.0.6
 3. Cleared  Javascript/Css and Static files cache 

**Issue description**
File algoliaAdminBundle.js in not loaded by requirejs and fails with exception, but algoliaAdminBundle.min.js is present:  http://prntscr.com/eff0pc
It brokes all grids in backend: http://prntscr.com/eff0vu

**Comment by JanPetr** [comment]
Thank you for the report @vmalyk, I'm looking at it right now.

**Comment by richdynamix** [comment]
I have also experienced this. Wrong URL for `algoliaAdminBundle.min.js`

**Comment by JanPetr** [comment]
Hello @vmalyk and @richdynamix, I fixed it in #168. Can you update to `dev-master` and try it out if it works on your side? I'll release it then ASAP. Thank you!

**Comment by vmalyk** [comment]
Fix has been working fine, but would be great to move requirejs.config to view/adminhtml/requirejs-config.js instead inline usage in template

**Comment by JanPetr** [comment]
Thanks for getting back to me @vmalyk! Can you check #169?

**Comment by vmalyk** [comment]
@JanPetr, Checked! Works good!

**Comment by JanPetr** [comment]
Thank you! I'm releasing a new version, thank you for your help @vmalyk 💯

**Comment by vmalyk** [comment]
did you update composer.json for new version?

**Comment by JanPetr** [comment]
No no, I released to soon. Fixing it now and releasing 1.0.8. Will be pushed in a while

**Comment by niekv** [comment]
Still experiencing this problem in latest version of the module. I applied your fix #168 and problem is fixed again. 

@vmalyk Do you also have the problem again in 1.7.2?
