### ISSUE TITLE
Composer Require Only Installs Version 1.80

### ISSUE THREAD

**Issue by nickpiro** [algolia/algoliasearch-magento-2#628]
Composer require only installs version 1.8.0, latest stable version 1.8.4

<img width="455" alt="algolia-composer" src="https://user-images.githubusercontent.com/36938969/49578688-51b2be00-f918-11e8-8fec-13363b02c186.png">

Magento 2.2.6

**Comment by JanPetr** [comment]
Thanks for creating the issue, it should be fixed now, @nickpiro 🚀

**Comment by nickpiro** [comment]
I'm still having an issue updating my module. Should i be running 
composer update algolia/algoliasearch-magento-2
or 
composer require algolia/algoliasearch-magento-2
to update the current module?

When I run composer update algolia/algoliasearch-magento-2 I am told there is nothing to import.
