### ISSUE TITLE
Add to cart from category page not updating

### ISSUE THREAD

**Issue by richdynamix** [algolia/algoliasearch-magento-2#98]
When clicking the add to cart button the search results and category pages the page refreshes displaying the success message across the top. - 

<img width="654" alt="screen shot 2016-11-02 at 17 06 47" src="https://cloud.githubusercontent.com/assets/1104549/19938967/d9d4c926-a11e-11e6-838d-54870f938df9.png">

Although you are presented with a success message the cart is not actually updated until you add something from a product page. For all pages up to this point it would appear as though the cart is empty - 

<img width="446" alt="screen shot 2016-11-02 at 17 08 08" src="https://cloud.githubusercontent.com/assets/1104549/19939015/0a8a4f6e-a11f-11e6-85c2-e0de808d8707.png">

The Add to Cart button on the product page uses AJAX to add the product, the success message is shown immediately and the mini cart is updated with products. At this point you can see previously added products from the category/search pages.

Default Magento 2 allows for AJAX add to cart functionality on category/search pages. This would appear to be a bug in the module as its not initialising the JS for the action.

This is noticeable on your demo site.

**Comment by JanPetr** [comment]
Hey @richdynamix, thanks for the report!
Will investigate and come back to you.

**Comment by richdynamix** [comment]
Hey @JanPetr Do you have any update on this?

**Comment by JanPetr** [comment]
Not yet @richdynamix, I didn't get to it yet.
I will try to investigate this week.

**Comment by JanPetr** [comment]
Hello @richdynamix,
I fixed it in #107. You can give it a try and it'll be part of the next release.

**Comment by richdynamix** [comment]
Tested with the latest `dev-master` branch and unfortunately the issue is still persistent. Full page refresh on category and search pages and mini basket is still not updated.

**Comment by JanPetr** [comment]
@richdynamix would you have live website where I could see that?

**Comment by richdynamix** [comment]
Apologies @JanPetr False alarm. I think it was a symptom of some heavy caching. I found it working on a category I have never visited before. But not on others. I can see the files have updated on my environment. Seems to work well :) Good job!

**Comment by JanPetr** [comment]
Great, thanks for getting back to me! I'll release RC version now.
